Secretary equipment branch
kzi-nastava/course-project-tim-3 pull request #81
Opened 2022-06-06 18:21 UTC by VuksanFilip

2022-06-06 19:17 UTC, swopl requested changes

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/EquipUI.cs
> +        System.Console.Write("Chose location: ");
*Choose

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/EquipUI.cs
> +        }
Extract to func

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +        // _loadedBatches = _hospital.EquipmentRepo.GetAll().ToList();
Again with the Serializable UI. That should not be serializable!! Also commented out useless stuff

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +             System.Console.WriteLine("   5. Delete patient-(dp)");
Fix indents

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +                    PagesUI pages = new PagesUI(_hospital);
BBB?

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +        }
Maybe use ReadSanitizedLine instead. Check it out

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +        }
For real? If you wanted to do something like this add a wrapper class that takes input and does a back if input back. Like a ReadPagedCommand (dont call it that if you make it) that returns a string or throws a Returning to menu exception

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +            // ur.AddOrUpdateUser(new User(email, password,patient,Role.PATIENT));
Useless commented code

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +            Console.Clear();
No matter what, at the end of this function it Clears the console. Why then not put it at end? Instead you put it in all of the ifs and else

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +        back = Console.ReadLine();
Indent. Also does this part  just force the user to type back? Why not just let him go after reading anything?

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +        Console.Clear();
Split this function

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +    {
You are only blocking one Patient. Also maybe shouldn't call it UserPatient

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +    //MAKE BETTER CONSOLE INTERFACE
If you make a TODO you should put at the start of the comment TODO:

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +        foreach(var b in blockedUsers){
b

2022-06-06 19:17 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +         us.UnblockPatient(email);
Indent

2022-06-07 00:02 UTC, VuksanFilip commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +             System.Console.WriteLine("   5. Delete patient-(dp)");
I do not understand?

2022-06-07 14:37 UTC, swopl commented on HospitalSystem.ConsoleUI/Secretary/CrudUI.cs
> +    {
Why is this function called block if it deletes? The code seems to be for blocking??

2022-06-07 14:53 UTC, VuksanFilip commented on HospitalSystem.ConsoleUI/Secretary/EquipUI.cs
> +        }
These were the old functions from the old file, one of my first functions... They have not been modified since then...

2022-06-07 17:08 UTC, VuksanFilip commented on HospitalSystem.ConsoleUI/Secretary/PagesUI.cs
> +            var user = usersList.ElementAt(i);
Do you really mind...?

2022-06-07 20:02 UTC, swopl approved these changes

2022-06-07 20:03 UTC, merged